const mongoose = require("mongoose");
const db = require("../models");
mongoose.Promise = global.Promise;

// This file empties the Books collection and inserts the books below

mongoose.connect(
  process.env.MONGODB_URI || "mongodb://localhost/clash"
);

const userSeed = [
  {
    userName: "testUser",
    passWord: "testPassword",
    ign: "testIGN",
    rank: "diamond",
    role: "top",
    captain: true,
    teamName: "FreeSM",
    server: "NA",
    schedule: {
      monday: {
        twelveAM: false,
        oneAM: false,
        twoAM: false,
        threeAM: false,
        fourAM: false,
        fiveAM: false,
        sixAM: false,
        sevenAM: false,
        eightAM: false,
        nineAM: false,
        tenAM: false,
        elevenAM: false,
        twevlePM: false,
        onePM: false,
        twoPM: true,
        threePM: true,
        fourPM: true,
        fivePM: true,
        sixPM: true,
        sevenPM: false,
        eightPM: false,
        ninePM: true,
        tenPM: true,
        elevenPM: false,
        twelvePM: false,
      },
      tuesday: {
        twelveAM: false,
        oneAM: false,
        twoAM: false,
        threeAM: false,
        fourAM: false,
        fiveAM: false,
        sixAM: false,
        sevenAM: false,
        eightAM: false,
        nineAM: false,
        tenAM: false,
        elevenAM: false,
        twevlePM: false,
        onePM: false,
        twoPM: true,
        threePM: true,
        fourPM: true,
        fivePM: true,
        sixPM: true,
        sevenPM: false,
        eightPM: false,
        ninePM: true,
        tenPM: true,
        elevenPM: false,
        twelvePM: false,
      },
      wednesday: {
        twelveAM: false,
        oneAM: false,
        twoAM: false,
        threeAM: false,
        fourAM: false,
        fiveAM: false,
        sixAM: false,
        sevenAM: false,
        eightAM: false,
        nineAM: false,
        tenAM: false,
        elevenAM: false,
        twevlePM: false,
        onePM: false,
        twoPM: false,
        threePM: false,
        fourPM: false,
        fivePM: false,
        sixPM: true,
        sevenPM: false,
        eightPM: false,
        ninePM: false,
        tenPM: false,
        elevenPM: false,
        twelvePM: false,
      },
      thursday: {
        twelveAM: false,
        oneAM: false,
        twoAM: false,
        threeAM: false,
        fourAM: false,
        fiveAM: false,
        sixAM: false,
        sevenAM: false,
        eightAM: false,
        nineAM: false,
        tenAM: false,
        elevenAM: false,
        twevlePM: false,
        onePM: false,
        twoPM: true,
        threePM: true,
        fourPM: true,
        fivePM: true,
        sixPM: true,
        sevenPM: false,
        eightPM: false,
        ninePM: true,
        tenPM: true,
        elevenPM: false,
        twelvePM: false,
      },
      friday: {
        twelveAM: false,
        oneAM: false,
        twoAM: false,
        threeAM: false,
        fourAM: false,
        fiveAM: false,
        sixAM: false,
        sevenAM: false,
        eightAM: false,
        nineAM: false,
        tenAM: false,
        elevenAM: false,
        twevlePM: false,
        onePM: false,
        twoPM: false,
        threePM: false,
        fourPM: false,
        fivePM: false,
        sixPM: true,
        sevenPM: false,
        eightPM: false,
        ninePM: false,
        tenPM: false,
        elevenPM: false,
        twelvePM: false,
      },
      saturday: {
        twelveAM: false,
        oneAM: false,
        twoAM: false,
        threeAM: false,
        fourAM: false,
        fiveAM: false,
        sixAM: false,
        sevenAM: false,
        eightAM: false,
        nineAM: false,
        tenAM: false,
        elevenAM: false,
        twevlePM: false,
        onePM: false,
        twoPM: true,
        threePM: true,
        fourPM: true,
        fivePM: true,
        sixPM: true,
        sevenPM: false,
        eightPM: false,
        ninePM: true,
        tenPM: true,
        elevenPM: false,
        twelvePM: false,
      },
      sunday: {
        twelveAM: false,
        oneAM: false,
        twoAM: false,
        threeAM: false,
        fourAM: false,
        fiveAM: false,
        sixAM: false,
        sevenAM: false,
        eightAM: false,
        nineAM: false,
        tenAM: false,
        elevenAM: false,
        twevlePM: false,
        onePM: false,
        twoPM: true,
        threePM: true,
        fourPM: true,
        fivePM: true,
        sixPM: true,
        sevenPM: false,
        eightPM: false,
        ninePM: true,
        tenPM: true,
        elevenPM: false,
        twelvePM: false,
      },
    }
  }
]

db.User
  .remove({})
  .then(() => db.User.collection.insertMany(userSeed))
  .then(data => {
    console.log("Seed inserted to DB!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
